baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "ScrapingBee"

# Disable RSS and taxonomies to avoid build errors
disableRSS = true
disableKinds = ["taxonomy", "term"]

[params]
  # Hero section
  [params.hero]
    heading = "Web Scraping Made Simple"
    intro = "Extract data from any website with our powerful web scraping API. Access real-time data, automate data collection, and scale your scraping projects without worrying about IP blocks or complex infrastructure."
    
    [[params.hero.cta_buttons]]
    text = "Explore Scrapers"
    url = "/scrapers"
    style = "primary"
    
    [[params.hero.cta_buttons]]
    text = "View Pricing"
    url = "#pricing"
    style = "secondary"

  # Navigation
  [[params.navigation]]
    title = "All Scrapers"
    url = "/scrapers"

  # Scrapers section
  [params.scrapers_section]
    heading = "Popular Scrapers"
    intro = "Ready-to-use scrapers for the most popular platforms and websites."

  # Footer sections
  [[params.footer_sections]]
    title = "ScrapingBee"
    heading_level = 3
    description = "Web scraping made simple and reliable. Extract data from any website with our powerful API."
  
  [[params.footer_sections]]
    title = "Products"
    heading_level = 4
    links = [
      { text = "Scrapers", url = "/scrapers" },
      { text = "API", url = "/api" },
      { text = "Pricing", url = "/pricing" }
    ]
  
  [[params.footer_sections]]
    title = "Resources"
    heading_level = 4
    links = [
      { text = "Documentation", url = "/docs" },
      { text = "Blog", url = "/blog" },
      { text = "Support", url = "/support" }
    ]
  
  [[params.footer_sections]]
    title = "Company"
    heading_level = 4
    links = [
      { text = "About", url = "/about" },
      { text = "Contact", url = "/contact" },
      { text = "Privacy", url = "/privacy" }
    ]
