[build]
  # Hugo build command with minification
  command = "hugo --minify"
  
  # Directory where Hugo outputs the built site
  publish = "public"

[build.environment]
  # Hugo version - using a stable recent version
  HUGO_VERSION = "0.120.0"
  
  # Environment variables for Hugo
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Build settings for different deployment contexts
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://your-domain.netlify.app"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"
  HUGO_BASEURL = "https://deploy-preview-{id}--your-site.netlify.app"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"
  HUGO_BASEURL = "https://{branch}--your-site.netlify.app"

# Redirects for better SEO and user experience
[[redirects]]
  # Handle 404s gracefully
  from = "/*"
  to = "/404.html"
  status = 404

# Security and performance headers
[[headers]]
  # Apply these headers to all pages
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Cache static assets longer for better performance
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache CSS files
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache JS files
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for the site
[context.production.environment]
  # Add any environment variables your site needs
  SITE_URL = "https://your-domain.netlify.app"
  API_URL = "https://api.scrapingbee.com"

[context.deploy-preview.environment]
  SITE_URL = "https://deploy-preview-{id}--your-site.netlify.app"
  API_URL = "https://api.scrapingbee.com" 